# 4.7 Deriving new variables

#### 1. import dataframes to notebook and chek shape

#### 2. Task step 2

#### 3. Task step 4

#### 4. Task step 5

#### 6. Task step 7

#### 7. Export to pickle format


## 1.

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os

#set scripts path in variable 'path'
path = r'/Users/constantinmelachrinos/Documents/careerfoundry data analyst/Course files/Data Analytics Immersion/Achievement 4 - InstaCart - Python/Instacart Basket Analysis'

#import Instacart data_sets
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merge_derived.pkl'))

In [3]:
#check shape
ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,1,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2539329,1,1,2,8,NaN,1,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
2,2539329,1,1,2,8,NaN,1,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders
3,2539329,1,1,2,8,NaN,1,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders
4,2539329,1,1,2,8,NaN,1,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders

# 2. Task step 2
### In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [4]:
#apply groupby and aggregation on dataframe
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

### Nothing really different as from the subset. Same amount of departments but the mean values are ofcourse somewhat different since more datasets are involved.

# 3.  Task step 4
### Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

In [5]:
#Group by user_id and apply transform function on order_number with max argument to find maximum orders
#write in new column 'max_order'
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [6]:
# check outcome on specific columns
ords_prods_merge[['user_id','order_number','max_order']].head(20)

    user_id  order_number  max_order
0         1             1         10
1         1             1         10
2         1             1         10
3         1             1         10
4         1             1         10
5         1             2         10
6         1             2         10
7         1             2         10
8         1             2         10
9         1             2         10
10        1             2         10
11        1             3         10
12        1             3         10
13        1             3         10
14        1             3         10
15        1             3         10
16        1             4         10
17        1             4         10
18        1             4         10
19        1             4         10

In [7]:
#Check with grouped by user_id
ords_prods_merge.groupby('user_id').agg({'order_number': ['max']}).head(20)

        order_number
                 max
user_id
1                 10
2                 14
3                 12
4                  5
5                  4
6                  3
7                 20
8                  3
9                  3
10                 5
11                 7
12                 5
13                12
14                13
15                22
16                 6
17                40
18                 6
19                 9
20                 4

In [8]:
#loc function for Loyale customer if orders over 40
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [9]:
#loc function for regular customer if orders between 11 and 40
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [10]:
#loc function for New customer if orders 10 or lower
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [11]:
#Count how many regular customers, Loyal customers and New customers.
ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

# 4.  Task step 5
### The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [12]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

### what is obvious is that the min and max dont differ. the mean price is the highest with new customers but that has probably to do with the less amount of data sets.

# 5. Task step 6
### The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:
### If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
### If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [13]:
#Group by user_id and apply transform function on prices with mean argument to find mean prices
#write in new column 'mean_prices'
ords_prods_merge['mean_prices'] = ords_prods_merge.groupby(['user_id'])['prices'].transform('mean')

In [14]:
#check if execution went accordingly
ords_prods_merge.head(60)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices
0,2539329,1,1,2,8,NaN,1,196,1,0,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
1,2539329,1,1,2,8,NaN,1,14084,2,0,...,16,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
2,2539329,1,1,2,8,NaN,1,12427,3,0,...,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
3,2539329,1,1,2,8,NaN,1,26088,4,0,...,19,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
4,2539329,1,1,2,8,NaN,1,26405,5,0,...,17,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
5,2398795,1,2,3,7,15.0,0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
6,2398795,1,2,3,7,15.0,0,10258,2,0,...,19,3.0,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
7,2398795,1,2,3,7,15.0,0,12427,3,1,...,19,4.4,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
8,2398795,1,2,3,7,15.0,0,13176,4,0,...,4,10.3,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
9,2398795,1,2,3,7,15.0,0,26088,5,1,...,19,4.7,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
10,2398795,1,2,3,7,15.0,0,13032,6,0,...,14,4.0,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797
11,473747,1,3,3,12,21.0,0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
12,473747,1,3,3,12,21.0,0,12427,2,1,...,19,4.4,both,Low-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
13,473747,1,3,3,12,21.0,0,10258,3,1,...,19,3.0,both,Low-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
14,473747,1,3,3,12,21.0,0,25133,4,0,...,16,8.6,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
15,473747,1,3,3,12,21.0,0,30450,5,0,...,13,3.2,both,Low-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797
16,2254736,1,4,4,7,29.0,0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
17,2254736,1,4,4,7,29.0,0,12427,2,1,...,19,4.4,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
18,2254736,1,4,4,7,29.0,0,10258,3,1,...,19,3.0,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
19,2254736,1,4,4,7,29.0,0,25133,4,1,...,16,8.6,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
20,2254736,1,4,4,7,29.0,0,26405,5,1,...,17,1.0,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
21,431534,1,5,4,15,28.0,0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
22,431534,1,5,4,15,28.0,0,12427,2,1,...,19,4.4,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
23,431534,1,5,4,15,28.0,0,10258,3,1,...,19,3.0,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
24,431534,1,5,4,15,28.0,0,25133,4,1,...,16,8.6,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
25,431534,1,5,4,15,28.0,0,10326,5,0,...,4,2.7,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
26,431534,1,5,4,15,28.0,0,17122,6,0,...,4,14.0,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
27,431534,1,5,4,15,28.0,0,41787,7,0,...,4,5.0,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
28,431534,1,5,4,15,28.0,0,13176,8,1,...,4,10.3,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797
29,3367565,1,6,2,7,19.0,0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
30,3367565,1,6,2,7,19.0,0,12427,2,1,...,19,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
31,3367565,1,6,2,7,19.0,0,10258,3,1,...,19,3.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
32,3367565,1,6,2,7,19.0,0,25133,4,1,...,16,8.6,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797
33,550135,1,7,1,9,20.0,0,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
34,550135,1,7,1,9,20.0,0,10258,2,1,...,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
35,550135,1,7,1,9,20.0,0,12427,3,1,...,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
36,550135,1,7,1,9,20.0,0,25133,4,1,...,16,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
37,550135,1,7,1,9,20.0,0,13032,5,1,...,14,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
38,3108588,1,8,1,14,14.0,0,12427,1,1,...,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
39,3108588,1,8,1,14,14.0,0,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
40,3108588,1,8,1,14,14.0,0,10258,3,1,...,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
41,3108588,1,8,1,14,14.0,0,25133,4,1,...,16,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
42,3108588,1,8,1,14,14.0,0,46149,5,0,...,7,13.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
43,3108588,1,8,1,14,14.0,0,49235,6,0,...,16,1.8,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
44,2295261,1,9,1,16,0.0,0,49235,1,1,...,16,1.8,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
45,2295261,1,9,1,16,0.0,0,46149,2,1,...,7,13.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
46,2295261,1,9,1,16,0.0,0,25133,3,1,...,16,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
47,2295261,1,9,1,16,0.0,0,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
48,2295261,1,9,1,16,0.0,0,10258,5,1,...,19,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
49,2295261,1,9,1,16,0.0,0,12427,6,1,...,19,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
50,2550362,1,10,4,8,30.0,0,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
51,2550362,1,10,4,8,30.0,0,46149,2,1,...,7,13.4,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
52,2550362,1,10,4,8,30.0,0,39657,3,0,...,19,6.8,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
53,2550362,1,10,4,8,30.0,0,38928,4,0,...,16,12.6,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
54,2550362,1,10,4,8,30.0,0,25133,5,1,...,16,8.6,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
55,2550362,1,10,4,8,30.0,0,10258,6,1,...,19,3.0,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
56,2550362,1,10,4,8,30.0,0,35951,7,0,...,16,1.3,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
57,2550362,1,10,4,8,30.0,0,13032,8,1,...,14,4.0,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
58,2550362,1,10,4,8,30.0,0,12427,9,1,...,19,4.4,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797
59,2168274,2,1,2,11,NaN,1,32792,1,0,...,19,5.2,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,14,Regular customer,7.515897

In [15]:
#loc function for low spending customers, mean price below 10
ords_prods_merge.loc[ords_prods_merge['mean_prices'] < 10, 'spending_behaviour'] = 'Low spender'

In [16]:
#loc function for high spending customers, mean price 10 or above
ords_prods_merge.loc[ords_prods_merge['mean_prices'] >= 10, 'spending_behaviour'] = 'High spender'

In [17]:
#check if executed correctly
ords_prods_merge.tail(60)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices,spending_behaviour
32404799,2129269,206209,8,3,17,22.0,0,43961,2,1,...,3.8,both,Low-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404800,2129269,206209,8,3,17,22.0,0,19348,3,1,...,4.6,both,Low-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404801,2129269,206209,8,3,17,22.0,0,13176,4,1,...,10.3,both,Mid-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404802,2129269,206209,8,3,17,22.0,0,6846,5,1,...,11.3,both,Mid-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404803,2129269,206209,8,3,17,22.0,0,17500,6,0,...,2.1,both,Low-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404804,2129269,206209,8,3,17,22.0,0,36056,7,0,...,13.6,both,Mid-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404805,2129269,206209,8,3,17,22.0,0,12376,8,0,...,11.5,both,Mid-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404806,2129269,206209,8,3,17,22.0,0,40992,9,1,...,1.8,both,Low-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404807,2129269,206209,8,3,17,22.0,0,33129,10,0,...,1.3,both,Low-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404808,2129269,206209,8,3,17,22.0,0,14870,11,0,...,2.1,both,Low-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404809,2129269,206209,8,3,17,22.0,0,16066,12,0,...,7.0,both,Mid-range product,Regularly busy,Least busy days,Average orders,13,Regular customer,7.058915,Low spender
32404810,2558525,206209,9,4,15,22.0,0,38167,1,1,...,5.8,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404811,2558525,206209,9,4,15,22.0,0,23892,2,1,...,9.1,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404812,2558525,206209,9,4,15,22.0,0,6846,3,1,...,11.3,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404813,2266710,206209,10,5,18,29.0,0,9405,1,1,...,11.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404814,2266710,206209,10,5,18,29.0,0,6846,2,1,...,11.3,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404815,2266710,206209,10,5,18,29.0,0,15700,3,0,...,2.3,both,Low-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404816,2266710,206209,10,5,18,29.0,0,26503,4,0,...,6.2,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404817,2266710,206209,10,5,18,29.0,0,41213,5,1,...,4.8,both,Low-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404818,2266710,206209,10,5,18,29.0,0,23800,6,0,...,6.2,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404819,2266710,206209,10,5,18,29.0,0,24852,7,0,...,12.3,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404820,2266710,206209,10,5,18,29.0,0,13838,8,0,...,3.8,both,Low-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404821,2266710,206209,10,5,18,29.0,0,31130,9,0,...,6.3,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,13,Regular customer,7.058915,Low spender
32404822,1854736,206209,11,4,10,30.0,0,6846,1,1,...,11.3,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404823,1854736,206209,11,4,10,30.0,0,9405,2,1,...,11.5,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404824,1854736,206209,11,4,10,30.0,0,41213,3,1,...,4.8,both,Low-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404825,1854736,206209,11,4,10,30.0,0,24852,4,1,...,12.3,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404826,1854736,206209,11,4,10,30.0,0,19348,5,1,...,4.6,both,Low-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404827,1854736,206209,11,4,10,30.0,0,15700,6,1,...,2.3,both,Low-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404828,1854736,206209,11,4,10,30.0,0,40310,7,0,...,1.9,both,Low-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404829,1854736,206209,11,4,10,30.0,0,48370,8,0,...,7.4,both,Mid-range product,Least busy,Least busy days,Most orders,13,Regular customer,7.058915,Low spender
32404830,626363,206209,12,1,12,18.0,0,6846,1,1,...,11.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404831,626363,206209,12,1,12,18.0,0,24852,2,1,...,12.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404832,626363,206209,12,1,12,18.0,0,9405,3,1,...,11.5,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404833,626363,206209,12,1,12,18.0,0,19348,4,1,...,4.6,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404834,626363,206209,12,1,12,18.0,0,41213,5,1,...,4.8,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404835,626363,206209,12,1,12,18.0,0,15700,6,1,...,2.3,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404836,626363,206209,12,1,12,18.0,0,38167,7,1,...,5.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404837,626363,206209,12,1,12,18.0,0,26209,8,0,...,14.7,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404838,626363,206209,12,1,12,18.0,0,33129,9,1,...,1.3,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404839,626363,206209,12,1,12,18.0,0,43961,10,1,...,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404840,626363,206209,12,1,12,18.0,0,23800,11,1,...,6.2,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404841,626363,206209,12,1,12,18.0,0,13838,12,1,...,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404842,626363,206209,12,1,12,18.0,0,48742,13,1,...,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404843,626363,206209,12,1,12,18.0,0,23594,14,1,...,3.7,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404844,626363,206209,12,1,12,18.0,0,20590,15,0,...,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404845,626363,206209,12,1,12,18.0,0,16168,16,0,...,11.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404846,626363,206209,12,1,12,18.0,0,33351,17,0,...,6.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404847,626363,206209,12,1,12,18.0,0,5622,18,0,...,8.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404848,626363,206209,12,1,12,18.0,0,23039,19,1,...,3.4,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404849,626363,206209,12,1,12,18.0,0,14727,20,0,...,3.2,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404850,2977660,206209,13,1,12,7.0,0,24852,1,1,...,12.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404851,2977660,206209,13,1,12,7.0,0,9405,2,1,...,11.5,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404852,2977660,206209,13,1,12,7.0,0,16168,3,1,...,11.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404853,2977660,206209,13,1,12,7.0,0,39216,4,0,...,3.3,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404854,2977660,206209,13,1,12,7.0,0,14197,5,1,...,5.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404855,2977660,206209,13,1,12,7.0,0,38730,6,0,...,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404856,2977660,206209,13,1,12,7.0,0,31477,7,0,...,4.2,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404857,2977660,206209,13,1,12,7.0,0,6567,8,0,...,4.9,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender
32404858,2977660,206209,13,1,12,7.0,0,22920,9,0,...,1.7,both,Low-range product,Regularly busy,Busiest days,Most orders,13,Regular customer,7.058915,Low spender

In [18]:
# check if executed correctly
ords_prods_merge.groupby(['user_id','mean_prices']).agg({'spending_behaviour': ['max']}).head(20)

                    spending_behaviour
                                   max
user_id mean_prices
1       6.367797           Low spender
2       7.515897           Low spender
3       8.197727           Low spender
4       8.205556           Low spender
5       9.189189           Low spender
6       8.471429           Low spender
7       7.466990           Low spender
8       8.781633           Low spender
9       7.607895           Low spender
10      8.651049           Low spender
11      8.328723           Low spender
12      8.116216           Low spender
13      8.708642           Low spender
14      8.014286           Low spender
15      3.980556           Low spender
16      8.228571           Low spender
17      108.648299        High spender
18      7.702564           Low spender
19      8.372059           Low spender
20      5.409091           Low spender

# 6. Task step 7
### In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
### If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
### If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
### If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [19]:
#Group by user_id and apply transform function on days_since_prior_order with mean argument to find mean days
#write in new column 'mean_prices'
ords_prods_merge['median_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform('mean')

In [20]:
ords_prods_merge.head(60)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices,spending_behaviour,median_days_since_prior_order
0,2539329,1,1,2,8,NaN,1,196,1,0,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
1,2539329,1,1,2,8,NaN,1,14084,2,0,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
2,2539329,1,1,2,8,NaN,1,12427,3,0,...,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
3,2539329,1,1,2,8,NaN,1,26088,4,0,...,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
4,2539329,1,1,2,8,NaN,1,26405,5,0,...,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
5,2398795,1,2,3,7,15.0,0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
6,2398795,1,2,3,7,15.0,0,10258,2,0,...,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
7,2398795,1,2,3,7,15.0,0,12427,3,1,...,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
8,2398795,1,2,3,7,15.0,0,13176,4,0,...,both,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
9,2398795,1,2,3,7,15.0,0,26088,5,1,...,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
10,2398795,1,2,3,7,15.0,0,13032,6,0,...,both,Low-range product,Regularly busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
11,473747,1,3,3,12,21.0,0,196,1,1,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
12,473747,1,3,3,12,21.0,0,12427,2,1,...,both,Low-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
13,473747,1,3,3,12,21.0,0,10258,3,1,...,both,Low-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
14,473747,1,3,3,12,21.0,0,25133,4,0,...,both,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
15,473747,1,3,3,12,21.0,0,30450,5,0,...,both,Low-range product,Regularly busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
16,2254736,1,4,4,7,29.0,0,196,1,1,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
17,2254736,1,4,4,7,29.0,0,12427,2,1,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
18,2254736,1,4,4,7,29.0,0,10258,3,1,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
19,2254736,1,4,4,7,29.0,0,25133,4,1,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
20,2254736,1,4,4,7,29.0,0,26405,5,1,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
21,431534,1,5,4,15,28.0,0,196,1,1,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
22,431534,1,5,4,15,28.0,0,12427,2,1,...,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
23,431534,1,5,4,15,28.0,0,10258,3,1,...,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
24,431534,1,5,4,15,28.0,0,25133,4,1,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
25,431534,1,5,4,15,28.0,0,10326,5,0,...,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
26,431534,1,5,4,15,28.0,0,17122,6,0,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
27,431534,1,5,4,15,28.0,0,41787,7,0,...,both,Low-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
28,431534,1,5,4,15,28.0,0,13176,8,1,...,both,Mid-range product,Least busy,Least busy days,Most orders,10,New customer,6.367797,Low spender,20.259259
29,3367565,1,6,2,7,19.0,0,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
30,3367565,1,6,2,7,19.0,0,12427,2,1,...,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
31,3367565,1,6,2,7,19.0,0,10258,3,1,...,both,Low-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
32,3367565,1,6,2,7,19.0,0,25133,4,1,...,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
33,550135,1,7,1,9,20.0,0,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
34,550135,1,7,1,9,20.0,0,10258,2,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
35,550135,1,7,1,9,20.0,0,12427,3,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
36,550135,1,7,1,9,20.0,0,25133,4,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
37,550135,1,7,1,9,20.0,0,13032,5,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
38,3108588,1,8,1,14,14.0,0,12427,1,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
39,3108588,1,8,1,14,14.0,0,196,2,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
40,3108588,1,8,1,14,14.0,0,10258,3,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
41,3108588,1,8,1,14,14.0,0,25133,4,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
42,3108588,1,8,1,14,14.0,0,46149,5,0,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
43,3108588,1,8,1,14,14.0,0,49235,6,0,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
44,2295261,1,9,1,16,0.0,0,49235,1,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
45,2295261,1,9,1,16,0.0,0,46149,2,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
46,2295261,1,9,1,16,0.0,0,25133,3,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
47,2295261,1,9,1,16,0.0,0,196,4,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
48,2295261,1,9,1,16,0.0,0,10258,5,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
49,2295261,1,9,1,16,0.0,0,12427,6,1,...,both,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.259259
50,2550362,1,10,4,8,30.0,0,196,1,1,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
51,2550362,1,10,4,8,30.0,0,46149,2,1,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
52,2550362,1,10,4,8,30.0,0,39657,3,0,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
53,2550362,1,10,4,8,30.0,0,38928,4,0,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
54,2550362,1,10,4,8,30.0,0,25133,5,1,...,both,Mid-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
55,2550362,1,10,4,8,30.0,0,10258,6,1,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
56,2550362,1,10,4,8,30.0,0,35951,7,0,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
57,2550362,1,10,4,8,30.0,0,13032,8,1,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
58,2550362,1,10,4,8,30.0,0,12427,9,1,...,both,Low-range product,Least busy,Least busy days,Average orders,10,New customer,6.367797,Low spender,20.259259
59,2168274,2,1,2,11,NaN,1,32792,1,0,...,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,14,Regular customer,7.515897,Low spender,15.967033

In [21]:
#loc function for non frequent customers, mean days higher 20
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] > 20, 'order_behaviour'] = 'Non-frequent customer'

In [22]:
#loc function for regular customers, mean days between 10 and 20 incl. 20 
ords_prods_merge.loc[(ords_prods_merge['median_days_since_prior_order'] > 10) & (ords_prods_merge['median_days_since_prior_order'] <= 20), 'order_behaviour'] = 'Regular customer'

In [23]:
#loc function for frequent customers, mean days lower or equal 10 days
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] <= 10, 'order_behaviour'] = 'Frequent customer'

In [24]:
#Check if all executed correctly by counting the frequency
ords_prods_merge['median_days_since_prior_order'].value_counts(dropna = False)

median_days_since_prior_order
30.000000    279604
7.000000      26118
14.000000     16417
18.000000     14954
16.000000     14512
              ...
0.888889         10
0.571429          8
0.166667          8
0.600000          7
NaN               5
Name: count, Length: 99563, dtype: int64

### obviously there is something wrong since there are 5 records with NaN values. Lets investigate

In [25]:
# show only NaN values in column 'median_days_since_prior_order'
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'].isnull()]

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,mean_prices,spending_behaviour,median_days_since_prior_order,order_behaviour
25156870,895835,159838,1,0,17,NaN,1,22198,1,0,...,Low-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
25156871,895835,159838,1,0,17,NaN,1,23695,2,0,...,Low-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
25156872,895835,159838,1,0,17,NaN,1,10749,3,0,...,Mid-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
25156873,895835,159838,1,0,17,NaN,1,21334,5,0,...,Mid-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN
25156874,895835,159838,1,0,17,NaN,1,33401,6,0,...,Mid-range product,Busiest day,Busiest days,Average orders,1,New customer,7.42,Low spender,NaN,NaN

### apparently there are new customers which only made one order. Lets hope they will order again :-)

In [27]:
# check for the number of out of range prices
ords_prods_merge['prices'].loc[ords_prods_merge['prices'] > 100]

1576        14900.0
1638        14900.0
16522       14900.0
16528       14900.0
53672       14900.0
             ...
32320511    14900.0
32347717    14900.0
32347727    14900.0
32380527    14900.0
32380551    14900.0
Name: prices, Length: 5127, dtype: float64

In [28]:
# replace these prices with NaN values
ords_prods_merge.loc[ords_prods_merge['prices'] >100, 'prices'] = np.nan

In [29]:
#check if executed correctly
ords_prods_merge['prices'].max()

25.0

# 7. Export

In [30]:
#export dataframe to pickle format
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_grouped.pkl'))